package com.joshuaduffill.quicksnap;

import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.graphics.Bitmap;
import android.media.MediaScannerConnection;
import android.net.Uri;
import android.os.Handler;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.MotionEvent;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.Toast;

import com.bumptech.glide.Glide;
import com.bumptech.glide.load.resource.drawable.GlideDrawable;
import com.bumptech.glide.request.RequestListener;
import com.bumptech.glide.request.target.Target;

import java.io.File;

public class FullScreenImageActivity extends AppCompatActivity implements View.OnLongClickListener, View.OnTouchListener{

    private ImageView fullScreenImageView;
    private ProgressBar mProgressBar;
    private Bitmap mPhotoBitmap;
    private Uri fileUri;

    // An object that manages Messages in a Thread
    private Handler mHandler;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // remove title
        setContentView(R.layout.activity_full_screen_image);

        mProgressBar = (ProgressBar) findViewById(R.id.progressBarImage);
        fullScreenImageView = (ImageView) findViewById(R.id.fullScreenImageView);

        //set listener method to image view
        fullScreenImageView.setOnLongClickListener(this);
        fullScreenImageView.setOnTouchListener(this);

        Intent callActivityIntent = getIntent();
        if(callActivityIntent != null){
            Uri imageUri = callActivityIntent.getData();
            fileUri = imageUri;
            if(imageUri != null && fullScreenImageView != null){
                Glide.with(this)
                        .load(imageUri)
                        .skipMemoryCache(true)
                        .listener(new RequestListener<Uri, GlideDrawable>() {
                            @Override
                            public boolean onException(Exception e, Uri model, Target<GlideDrawable> target, boolean isFirstResource) {
                                mProgressBar.setVisibility(View.GONE);
                                return false;
                            }
                            @Override
                            public boolean onResourceReady(GlideDrawable resource, Uri model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                                mProgressBar.setVisibility(View.GONE);
                                return false;
                            }
                        })
                        .into(fullScreenImageView);
                Toast.makeText(this, imageUri.getPath(), Toast.LENGTH_SHORT).show();
            }
        }


    }


    @Override
    public void onWindowFocusChanged(boolean hasFocus){
        super.onWindowFocusChanged(hasFocus);
        View decorView = getWindow().getDecorView();
        if(hasFocus){
            decorView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE
//            | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
//            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
//            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
//            | View.SYSTEM_UI_FLAG_FULLSCREEN
//            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
            | View.SYSTEM_UI_FLAG_FULLSCREEN);
        }

    }

    Thread clearCache = new Thread(){
        @Override
        public void run() {
            try{
                Glide.get(getApplicationContext()).clearDiskCache();

            }catch (Exception ex){
                ex.printStackTrace();
            }
        }
    };


    public boolean onOptionsItemSelected(MenuItem item) {

        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
//        int id = item.getItemId();
        switch (item.getItemId()){
            case R.id.option_delete:
                try{

//                    if (fileUri != null){
//
//                        //gets fileUri path and deletes the file
//                        File deleteFile = new File(fileUri.getPath());
//
//
//
//                        //updates Media Store, so no cache image is being generated by GLIDE.
////                        sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.fromFile(deleteFile)));
//
//                        Intent deleteScanIntent = new Intent (Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.fromFile(deleteFile));
//                        sendBroadcast(deleteScanIntent);
//
//
////                        sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.parse(fileUri.getPath() +  Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM))));
//
////                        File file= new File(android.os.Environment.getExternalStorageDirectory(), fileUri.getPath());
////                        if(file.exists())
////                        {
////                            boolean deleted = file.delete();
////                        }
//
//                        boolean deleted = deleteFile.delete();
//
//                        Toast.makeText(this, "Image deleted", Toast.LENGTH_SHORT).show();
//
//
//
//
//
//                        //closes activity
////                        Snackbar mysnackbar = Snackbar.make(findViewById(R.id.fullScreenImageView), "Hello there!", Snackbar.LENGTH_LONG);
////                        mysnackbar.setAction("Action", null).show();
//                    }else{
//
//                    }


                    AlertDialog diaBox = DeleteConfirmation();
                    diaBox.show();







                }catch(Exception ex){

                }
                return true;
            case R.id.option_edit:
                try{


                    Intent editImageIntent = new Intent(this, EditImageActivity.class);
                    editImageIntent.setData(fileUri);
                    startActivity(editImageIntent);

                }catch(Exception ex){

                }
            case R.id.option_share:
                try{
                    Intent shareIntent = createShareIntent();
                    startActivity(Intent.createChooser(shareIntent, "send to"));
                }catch(Exception ex){

                }

                //add more here
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    private Intent createShareIntent(){
        Intent shareIntent = new Intent(Intent.ACTION_SEND);
        shareIntent.setType("image/*");
        shareIntent.putExtra(Intent.EXTRA_STREAM, fileUri);
        return shareIntent;
    }

    private AlertDialog DeleteConfirmation()
    {

        AlertDialog mDeleteConfirmDialog =new AlertDialog.Builder(this)
                //set message, title, and icon
                .setTitle("Delete")
                .setMessage("Are you sure you want to delete this image?")
                .setIcon(R.mipmap.ic_delete_forever)

                .setPositiveButton("Delete", new DialogInterface.OnClickListener() {

                    public void onClick(DialogInterface dialog, int whichButton) {

                        if (fileUri != null) {

                            //gets fileUri path and deletes the file
                            File deleteFile = new File(fileUri.getPath());

                            boolean deleted = deleteFile.delete();

                            //updates
                            MediaScannerConnection.scanFile(getApplicationContext(), new String[]{fileUri.getPath()}, null,
                                    new MediaScannerConnection.OnScanCompletedListener() {
                                        @Override
                                        public void onScanCompleted(String path, Uri uri) {
                                            Log.v("Joshuaduffill",
                                                    "file" + path + "was scanned successfully: " + uri);
                                        }
                                    }

                            );

                        }

                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                Glide.get(getApplicationContext()).clearDiskCache();
                            }
                        }).start();

                        dialog.dismiss();
                        finish();

                    }


                })



                .setNegativeButton("cancel", new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int which) {

                        dialog.dismiss();

                    }
                })
                .create();
        return mDeleteConfirmDialog;

    }


    // https://developer.android.com/training/multiple-threads/define-runnable.html

    //https://stackoverflow.com/questions/1921514/how-to-run-a-runnable-thread-in-android

//    Thread renderingThread = new Thread(){
//        @Override
//        public void run() {
//            try{
//                //renders grayscale image
//                ImageProcessor imageProcessor = new ImageProcessor();
//                fullScreenImageView.setImageBitmap(imageProcessor.doGreyScale(mPhotoBitmap));
//
//            }catch (Exception ex){
//                ex.printStackTrace();
//            }
//
//    };

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.full_image_menu, menu);
        return true;
    }


    @Override
    public boolean onLongClick(View v) {
        AlertDialog diaBox = DeleteConfirmation();
        diaBox.show();
        return true;
    }

    @Override
    public boolean onTouch(View v, MotionEvent event) {
        Toast.makeText(this, "one touch", Toast.LENGTH_SHORT).show();
        //runs loop once pressed
        return false;
    }
}

